const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");

const generateTripInvoice = async (reservation, trip, user) => {
  const invoiceDir = path.join(__dirname, "../invoices");
  if (!fs.existsSync(invoiceDir)) fs.mkdirSync(invoiceDir, { recursive: true });

  const filePath = path.join(invoiceDir, `trip-invoice-${reservation._id}.pdf`);
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const stream = fs.createWriteStream(filePath);
  doc.pipe(stream);

  // ✅ Watermark
  doc
    .fontSize(60)
    .fillColor("gray")
    .opacity(0.2)
    .rotate(45, { origin: [250, 300] })
    .text("BanglaBnB", 100, 150);
  doc.rotate(-45).opacity(1); // reset

  // ✅ Header with logo
  const logoPath = path.join(__dirname, "../assets/banglabnb-logo.png");
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, 50, 40, { width: 100 });
  }

  doc
    .fontSize(18)
    .fillColor("black")
    .text("🧾 Trip Reservation Invoice", 200, 50);

  // ✅ Reservation details
  doc.fontSize(12).moveDown().text(`Invoice ID: ${reservation._id}`);
  doc.text(`Passenger: ${user.name}`);
  doc.text(`Trip: ${trip.from} ➡ ${trip.to}`);
  doc.text(`Date: ${trip.date}`);
  doc.text(`Time: ${trip.time}`);
  doc.text(`Seats Reserved: ${reservation.numberOfSeats}`);
  doc.text(`Fare per Seat: ৳${reservation.farePerSeat}`);
  doc.text(`Total Paid: ৳${reservation.totalAmount}`);

  // ✅ QR Code
  const qrData = `Trip ID: ${trip._id}, Reservation ID: ${reservation._id}, Amount: ৳${reservation.totalAmount}`;
  const qrImage = await QRCode.toDataURL(qrData);
  doc.image(qrImage, 400, 250, { width: 100 });

  // ✅ Footer
  doc.moveDown(4);
  doc.fontSize(10).fillColor("gray").text("Generated by BanglaBnB", {
    align: "center",
  });

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
  });
};

module.exports = generateTripInvoice;
