const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");

const generateInvoice = async (booking, listing, guest) => {
  return new Promise(async (resolve, reject) => {
    const invoiceDir = path.join(__dirname, "../invoices");
    if (!fs.existsSync(invoiceDir))
      fs.mkdirSync(invoiceDir, { recursive: true });

    const filePath = path.join(invoiceDir, `invoice-${booking._id}.pdf`);
    const qrPath = path.join(invoiceDir, `qr-${booking._id}.png`);
    const doc = new PDFDocument({ size: "A4", margin: 50 });

    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const logoPath = path.join(__dirname, "../assets/banglabnb-logo.png");
    const banglaFontPath = path.join(
      __dirname,
      "../fonts/NotoSansBengali-VariableFont_wdth,wght.ttf"
    );

    if (fs.existsSync(banglaFontPath)) {
      doc.registerFont("Bangla", banglaFontPath);
    }

    // 🔷 Header background and logo
    doc.rect(0, 0, 600, 100).fill("#e6f2f0");
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 50, 30, { width: 80 });
    }

    doc
      .fillColor("#006a4e")
      .font("Helvetica-Bold")
      .fontSize(22)
      .text("BanglaBnB", 150, 35, { align: "right" })
      .fontSize(14)
      .fillColor("#d21034")
      .text("📄 Booking Invoice", { align: "right" });

    doc.moveTo(50, 110).lineTo(550, 110).stroke();

    const nights = Math.ceil(
      (new Date(booking.dateTo) - new Date(booking.dateFrom)) /
        (1000 * 60 * 60 * 24)
    );
    const baseRate = listing.price;
    const baseTotal = baseRate * nights;
    const serviceFee = baseTotal * 0.1;
    const tax = (baseTotal + serviceFee) * 0.1;
    const total = baseTotal + serviceFee + tax;

    const formatCurrency = (val) => `BDT${val.toFixed(2)}`;

    // 🧾 Booking Info
    doc
      .fillColor("black")
      .font("Helvetica")
      .fontSize(11)
      .text(`Booking ID: ${booking._id}`)
      .text(`Guest: ${guest.name} (${guest.email})`)
      .text(`Listing: ${listing.title}`)
      .text(`Address: ${listing.location?.address}`)
      .text(
        `Dates: ${new Date(booking.dateFrom).toLocaleDateString()} → ${new Date(
          booking.dateTo
        ).toLocaleDateString()}`
      )
      .text(`Status: ${booking.paymentStatus}`)
      .moveDown();

    // 🌐 Bangla section
    doc
      .font("Bangla")
      .fillColor("#333")
      .fontSize(11)
      .text(`অতিথি: ${guest.name}`)
      .text(`মেইল: ${guest.email}`)
      .text(`অবস্থান: ${listing.location?.address}`)
      .text(
        `তারিখ: ${new Date(booking.dateFrom).toLocaleDateString()} → ${new Date(
          booking.dateTo
        ).toLocaleDateString()}`
      )
      .moveDown();

    // 💵 Price Breakdown
    doc
      .font("Helvetica-Bold")
      .fillColor("black")
      .fontSize(13)
      .text("💵 Payment Summary", { underline: true });
    doc.font("Helvetica").fontSize(12);

    const left = 60,
      right = 500;
    doc
      .text(
        `Nightly Rate (${formatCurrency(baseRate)} x ${nights} nights):`,
        left
      )
      .text(formatCurrency(baseTotal), right, doc.y, { align: "right" })
      .text("Service Fee (10%):", left)
      .text(formatCurrency(serviceFee), right, doc.y, { align: "right" })
      .text("VAT (10%):", left)
      .text(formatCurrency(tax), right, doc.y, { align: "right" })
      .font("Helvetica-Bold")
      .text("Total Amount Paid:", left)
      .text(formatCurrency(total), right, doc.y, { align: "right" });

    // 🧾 Invoice Number and Date
    doc
      .moveDown()
      .font("Helvetica")
      .fontSize(11)
      .fillColor("gray")
      .text(`Invoice Number: INV-${booking._id}`, left)
      .text(`Issued on: ${new Date().toLocaleDateString("en-GB")}`, left);

    // 🖨 QR Code
    await QRCode.toFile(
      qrPath,
      `https://banglabnb.com/bookings/${booking._id}`,
      { width: 100 }
    );
    doc.image(qrPath, right - 10, doc.y - 60, { width: 80 });

    // ✍️ Signature Section
    doc
      .moveDown(6)
      .fontSize(12)
      .fillColor("black")
      .text("__________________________", left, doc.y)
      .text("Guest Signature", left, doc.y)
      .text("__________________________", right - 180, doc.y - 30)
      .text("Authorized Signature", right - 180, doc.y);

    // 🔻 Footer Strip
    doc.rect(0, 760, 600, 40).fill("#f0f0f0");
    doc
      .fillColor("gray")
      .fontSize(10)
      .text("This invoice was automatically generated by BanglaBnB", 50, 775, {
        align: "center",
      });

    doc.end();

    stream.on("finish", () => {
      resolve(filePath);
      fs.unlink(qrPath, () => {});
    });

    stream.on("error", reject);
  });
};

module.exports = generateInvoice;
