const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");
const { cloudinary } = require("../config/cloudinary");

const generateInvoice = async (booking, listing, guest) => {
  return new Promise(async (resolve, reject) => {
    const invoiceDir = path.join(__dirname, "../invoices");
    if (!fs.existsSync(invoiceDir))
      fs.mkdirSync(invoiceDir, { recursive: true });

    const fileName = `invoice-${booking._id}.pdf`;
    const filePath = path.join(invoiceDir, fileName);
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // 🖼 Add Logo
    const logoPath = path.join(__dirname, "../assets/banglabnb-logo.png");
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 50, 45, { width: 120 });
    }

    // 🟢 Invoice Header with BD Flag Colors
    doc
      .fillColor("#006a4e") // dark green
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("BanglaBnB", 200, 50, { align: "right" })
      .fontSize(14)
      .fillColor("#e62e04") // red
      .text("📄 Booking Invoice / বুকিং চালান", { align: "right" })
      .moveDown();

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    // 🔢 Invoice Info
    doc
      .fontSize(12)
      .fillColor("black")
      .text(`Invoice #: ${booking._id}`)
      .text(`চালান নম্বরঃ ${booking._id}`)
      .text(`Status: ${booking.paymentStatus || "unpaid"}`)
      .text(
        `অবস্থা: ${booking.paymentStatus === "paid" ? "পরিশোধিত" : "অপরিশোধিত"}`
      )
      .moveDown();

    // 👤 Guest Info
    doc
      .text(`Guest: ${guest.name} (${guest.email})`)
      .text(`অতিথিঃ ${guest.name}`)
      .text(`Listing: ${listing.title}`)
      .text(`স্থানঃ ${listing.location?.address}`)
      .text(
        `Dates: ${new Date(booking.dateFrom).toLocaleDateString()} → ${new Date(
          booking.dateTo
        ).toLocaleDateString()}`
      )
      .text(
        `তারিখঃ ${new Date(booking.dateFrom).toLocaleDateString(
          "bn-BD"
        )} → ${new Date(booking.dateTo).toLocaleDateString("bn-BD")}`
      )
      .moveDown();

    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    // 💵 Pricing Summary
    const nights =
      (new Date(booking.dateTo) - new Date(booking.dateFrom)) /
      (1000 * 60 * 60 * 24);
    const baseRate = listing.price;
    const serviceFee = 100;
    const total = baseRate * nights + serviceFee;

    doc
      .moveDown(1)
      .fontSize(13)
      .text("💵 Price Breakdown / মূল্য বিবরণী", { underline: true });

    const formatCurrency = (val) => `৳${val.toFixed(2)}`;

    doc
      .fontSize(12)
      .text(`Nightly Rate (৳${baseRate} x ${nights} nights):`, 50)
      .text(`প্রতি রাতের দাম (${nights} রাত):`, 50, doc.y + 15)
      .text(formatCurrency(baseRate * nights), 0, doc.y - 15, {
        align: "right",
      })
      .moveDown(1)
      .text(`Service Fee:`, 50)
      .text(`সার্ভিস ফি:`, 50, doc.y + 15)
      .text(formatCurrency(serviceFee), 0, doc.y - 15, { align: "right" })
      .moveDown(1)
      .font("Helvetica-Bold")
      .text(`Total Amount Paid:`, 50)
      .text(`মোট পরিশোধিত অর্থঃ`, 50, doc.y + 15)
      .text(formatCurrency(total), 0, doc.y - 15, { align: "right" })
      .font("Helvetica")
      .moveDown(2);

    // 📦 QR Code
    const qrContent = `BanglaBnB Invoice\nBooking ID: ${booking._id}\nGuest: ${
      guest.name
    }\nTotal: ${formatCurrency(total)}`;
    const qrDataURL = await QRCode.toDataURL(qrContent);

    const qrImgPath = path.join(invoiceDir, `qr-${booking._id}.png`);
    const base64Data = qrDataURL.replace(/^data:image\/png;base64,/, "");
    fs.writeFileSync(qrImgPath, base64Data, "base64");

    doc.image(qrImgPath, 400, doc.y, { fit: [120, 120] }).moveDown(2);

    doc
      .fontSize(10)
      .fillColor("gray")
      .text("This invoice was automatically generated by BanglaBnB", {
        align: "center",
      });

    doc.end();

    // Wait for PDF stream
    stream.on("finish", async () => {
      // ☁️ Upload to Cloudinary
      try {
        const result = await cloudinary.uploader.upload(filePath, {
          folder: "banglabnb/invoices",
          resource_type: "raw", // for PDF
        });
        resolve(result.secure_url);
        fs.unlink(filePath, (err) => {
          if (err) console.warn("⚠️ Could not delete local PDF:", err);
        });

        fs.unlink(qrImgPath, (err) => {
          if (err) console.warn("⚠️ Could not delete QR image:", err);
        });
      } catch (uploadErr) {
        console.error("❌ Cloudinary Upload Failed:", uploadErr);
        reject(uploadErr);
      }
    });

    stream.on("error", reject);
  });
};

module.exports = generateInvoice;
