const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

const generateInvoice = async (booking, listing, guest) => {
  return new Promise((resolve, reject) => {
    const invoiceDir = path.join(__dirname, "../invoices");
    if (!fs.existsSync(invoiceDir))
      fs.mkdirSync(invoiceDir, { recursive: true });

    const filePath = path.join(invoiceDir, `invoice-${booking._id}.pdf`);
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    // 🖼 Add Logo (make sure this path is correct)
    const logoPath = path.join(__dirname, "../assets/banglabnb-logo.png");
    if (fs.existsSync(logoPath)) {
      doc.image(logoPath, 50, 45, { width: 100 });
    }

    // Header Text
    doc
      .fillColor("#006a4e") // Green from BD flag
      .fontSize(24)
      .text("BanglaBnB", 160, 50, { align: "right" });

    doc
      .fontSize(14)
      .fillColor("#f42a41") // Red from BD flag
      .text("📄 Booking Invoice", { align: "right" });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    // Booking Info
    doc
      .font("Helvetica")
      .fillColor("black")
      .fontSize(12)
      .moveDown()
      .text(`📌 Booking ID: ${booking._id}`)
      .text(`👤 Guest: ${guest.name} (${guest.email})`)
      .text(`🏠 Listing: ${listing.title}`)
      .text(`📍 Location: ${listing.location?.address}`)
      .text(
        `📅 Dates: ${new Date(
          booking.dateFrom
        ).toLocaleDateString()} → ${new Date(
          booking.dateTo
        ).toLocaleDateString()}`
      );

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();

    // 💵 Price Breakdown
    const nights =
      (new Date(booking.dateTo) - new Date(booking.dateFrom)) /
      (1000 * 60 * 60 * 24);
    const baseRate = listing.price;
    const serviceFee = 100;
    const total = baseRate * nights + serviceFee;

    const formatCurrency = (val) => `৳${val.toFixed(2)}`;

    doc
      .moveDown(1)
      .fontSize(13)
      .fillColor("#006a4e")
      .text("💵 Price Breakdown", { underline: true });

    doc
      .fontSize(12)
      .fillColor("black")
      .text(`Nightly Rate (৳${baseRate} x ${nights} nights):`, 50)
      .text(formatCurrency(baseRate * nights), { align: "right" })
      .text("Service Fee:", 50)
      .text(formatCurrency(serviceFee), { align: "right" })
      .font("Helvetica-Bold")
      .text("Total:", 50)
      .text(formatCurrency(total), { align: "right" });

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(10)
      .fillColor("gray")
      .text("This invoice was automatically generated by BanglaBnB", {
        align: "center",
      });

    doc.end();
    stream.on("finish", () => resolve(filePath));
    stream.on("error", reject);
  });
};

module.exports = generateInvoice;
